/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSnackbar: typeof import('./src/shared/components/AppSnackbar.vue')['default']
    OrderDialog: typeof import('./src/modules/orders/components/OrderDialog.vue')['default']
    OrdersTable: typeof import('./src/modules/orders/components/OrdersTable.vue')['default']
    ProductDialog: typeof import('./src/modules/products/components/ProductDialog.vue')['default']
    ProductsTable: typeof import('./src/modules/products/components/ProductsTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
